name: veripic
description: VeriPic - Tamper-Proof Geotagged Camera & Verification System.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

  # Camera + location
  camera: ^0.10.6
  geolocator: ^11.0.0
  permission_handler: ^11.3.1

  # Crypto + image processing
  crypto: ^3.0.3
  pointycastle: ^3.9.1
  image: ^4.9.1

  # Storage + env + networking
  flutter_secure_storage: ^9.2.2
  flutter_dotenv: ^5.1.0
  http: ^1.2.2
  path_provider: ^2.1.3
  image_picker: ^1.1.2
  intl: ^0.20.3
  device_info_plus: ^10.1.0
  android_id: ^0.5.2
  gal: ^2.3.3
  geocoding: ^3.0.0

dev_dependencies:
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - .env